#!/usr/bin/env bash
# bash script: to pull domain dns records
domain=$1
if [ "$#" -eq 1 ]; then
	subdom=("www" "lb-01" "web-01" "web-02")
else
	subdom=$2
fi
# Loop through the subdomains and query DNS information
for sub in "${subdom[@]}"; do
    echo -n "The subdomain $sub"
    dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | tail -n -1 | awk '{ print " is a "$4" record and points to "$5 }'
done
