#!/usr/bin/env bash
# bash script: to pull domain dns records
domain=$1
if [ "$#" -eq 2 ]; then
	subdom=$2
else
	subdom=("www" "lb-01" "web-01" "web-02")
fi
# Loop through the subdomains and query DNS information
for sub in "${subdom[@]}"; do
    echo -n "The subdomain $sub"
    result=$(dig "$sub.$domain" +short)
    
    if [ -n "$result" ]; then
        echo " is a DNS record and points to $result"
    else
        echo " does not exist."
    fi
done
