#!/usr/bin/env bash
# bash script to transfer file from client to server
if [ $# -lt 4 ]; then
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY';
	exit 1;
else
	scp -o strictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
	exit 0;
fi
