#!/usr/bin/env bash
# bash script to install nginx script
# index configuration + listen on port 80
sudo apt update -y
sudo apt install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
