#!/usr/bin/env bash
# bash script to install nginx script
# index configuration + listen on port 80
sudo apt-get update -y
sudo apt-get install -y nginx
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
echo "server {
	listen 80;
	server_name localhost;
}" > /etc/nginx/sites-available/default
sudo service nginx start
