#!/usr/bin/env bash
#bash script: to configure nginx server
# set up error page
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
replacement=$'\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n'
nginx_sites="/etc/nginx/sites-available/default"
location=$(grep -Fn "location" "$nginx_sites" | head -1 | cut -d":" -f1)
sudo sed -i "${location}i ${replacement}" "$nginx_sites"
sudo service nginx start
