#!/usr/bin/env bash
#bash script: to configure nginx server
# set up error page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
replacment="\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n"
nginx_sites="/etc/nginx/sites-available/default"
location=$(grep -Fn location $nginx_sites | head -1 | cut -d":" -f1)
sudo sed -i "${location}i ${replacment}" ${nginx_sites}
sudo service nginx start
