#!/usr/bin/env bash
#bash script: to configure nginx server
# set up error page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
replacement="server_name _;\n\trewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-enabled/default
sudo sed -i "s/server_name \\\terror_page 404 /404.html;\n" "/etc/nginx/sites-available/default"
sudo service nginx restart
