#!/usr/bin/env bash
#bash script: to configure nginx server
# set up error page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
replacment="\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n"
nginx_sites="/etc/nginx/sites-available/default"
location=$(grep -Fn location $nginx_sites | head -1 | cut -d":" -f1)
page404="\\\terror_page 404 /404.html;\n"
echo "Ceci n'est pas une page" | sudo tee "/var/www/html/404.html"
sudo sed -i "${location}i ${replacment}" ${nginx_sites}
sudo sed -i "${location}i ${page404}" ${nginx_sites}
sudo service nginx start
