#!/usr/bin/env bash
# Bash script to update and configure an Ubuntu server with Nginx

# apt operations
sudo apt update -y
sudo apt install nginx -y

# Configuration variables
alx_nginxDefaultSites="/etc/nginx/sites-enabled/default"
alx_defaultPage="/var/www/html/index.nginx-debian.html"
alx_defaultMessage="Hello World!"

new_config="
\tlocation /redirect_me {
\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
\t}

\tadd_header X-Served-By \"$(hostname)\";
"
## Implementations
echo "$alx_defaultMessage" | sudo tee "$alx_defaultPage" # Create default index
sudo sed -i -e "/server_name _;/ {
    n; a \\
$new_config
}" $alx_nginxDefaultSites # Update Nginx default configuration
sudo service nginx restart # Restart service
