#!/usr/bin/env bash
#Bash script to display "Best School" 10 times, on 9th iteration, display "Best School" followed by "Hi" in a new line.
i=0
while [ $i -lt 10 ]
do
	echo "Best School"
	((i++))
	if [ "$i" -eq 9 ]
	then
		echo "Hi"
	fi
done
