#!/usr/bin/env bash
#Bash script: iterate from 1 to 10 and display bad luck for the 4th iteration, and for 8th iteration good luck, otherwise best school
i=0
while [ $i -lt 10 ]
do
	if [ "$i" -eq 3 ]
	then
		echo "bad luck"
	elif [ "$i" -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
