#!/usr/bin/env bash
#Bash Script: configuration script for a ubuntu server
cp /etc/hosts ~/hosts.tmp
echo "127.0.0.2	localhost" >> ~/hosts.tmp
echo "8.8.8.8	facebook.com" >> ~/hosts.tmp
cp -f ~/hosts.tmp /etc/hosts
