#!/usr/bin/env bash
# bash script to fix container so that Nginx is running as the nginx user
pkill apache2
sudo sed -Ei 's/\s*#?s*user .*/user nginx;' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart 
