#!/usr/bin/env bash
# bash script to fix container so that Nginx is running as the nginx user
pkill apache2
sudo sed -i 's/# user www-data/user nginx/g' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginxs.conf
sudo -u nginx service nginx restart 
